server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka

spring:
  application:
    name: revelation-gateway
  cloud:
    gateway:
      routes:
        - id: game-service
          uri: lb://revelation-game
          predicates:
            - Path=/game/**
          filters:
            - StripPrefix=1
springdoc:
  swagger-ui:
    config-url: /swagger-config.json

revelation:
  custom-swagger:
    host-name: ${HOST_NAME:http://localhost:8080}
    url-prefixes:
      - game
