spring:
  application:
    name: revelation-gateway
  cloud:
    discovery:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka

server:
  port: 8080