spring:
  application:
    name: revelation-gateway
  cloud:
    gateway:
      routes:
        - id: game-service
          uri: lb://revelation-game
          predicates:
            - Path=/game/**
          filters:
            - StripPrefix=1
org:
  springframework:
    cloud:
      gateway: DEBUG


eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka
server:
  port: 8080
logging:
  level:
    reactor:
      netty: DEBUG
    org:
      springframework:
        cloud:
          gateway: DEBUG
