spring:
  application:
    name: revelation-gateway
  cloud:
    discovery:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761}/eureka

server:
  port: 8080